version: '3'

services:

  node:
    image: node:13.3.0-alpine
    container_name: thaitravelcenter-react-web
    restart: always
    logging:
      driver: "json-file"
      options:
          max-file: "1"
          max-size: 28kb
    entrypoint: yarn start
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:3000
      - 3001:3001
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
          
  install:
    image: node:13.3.0-alpine
    restart: always
    command: yarn
    working_dir: /app
    volumes:
      - ./:/app